services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.22.0
    container_name: mlflow
    env_file:
      - .env
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0



  nginx:
    image: nginx:alpine
    container_name: mlflow-nginx
    depends_on:
      - mlflow
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro

networks:
  meme-net: # Use the EXACT name defined in the producer
    external: true